import { Fjalla_One, Public_Sans } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publicSans = Public_Sans({ subsets: ["latin"], variable: "--font-sans" });

const fjalla = Fjalla_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-fjalla",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cn("font-sans", publicSans.variable)} ${cn("font-fjalla", fjalla.variable)}`}
    >
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
